<?php

namespace ContainerEQOmRUh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4HCB9nmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4HCB9nm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4HCB9nm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'albumRepository' => ['privates', 'App\\Repository\\AlbumRepository', 'getAlbumRepositoryService', true],
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'albumRepository' => 'App\\Repository\\AlbumRepository',
            'mediaRepository' => 'App\\Repository\\MediaRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
