<?php

namespace ContainerEQOmRUh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MjzZ5jvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MjzZ5jv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MjzZ5jv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\AlbumController::add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\Admin\\AlbumController::delete' => ['privates', '.service_locator.mUnGTpI', 'get_ServiceLocator_MUnGTpIService', true],
            'App\\Controller\\Admin\\AlbumController::index' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\Admin\\AlbumController::update' => ['privates', '.service_locator.mUnGTpI', 'get_ServiceLocator_MUnGTpIService', true],
            'App\\Controller\\Admin\\MediaController::add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\Admin\\MediaController::delete' => ['privates', '.service_locator.KP3PVQ0', 'get_ServiceLocator_KP3PVQ0Service', true],
            'App\\Controller\\Admin\\MediaController::index' => ['privates', '.service_locator.6zRW84N', 'get_ServiceLocator_6zRW84NService', true],
            'App\\Controller\\Admin\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\HomeController::guest' => ['privates', '.service_locator.fezAdO7', 'get_ServiceLocator_FezAdO7Service', true],
            'App\\Controller\\HomeController::guests' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\HomeController::portfolio' => ['privates', '.service_locator.4HCB9nm', 'get_ServiceLocator_4HCB9nmService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AlbumController:add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\Admin\\AlbumController:delete' => ['privates', '.service_locator.mUnGTpI', 'get_ServiceLocator_MUnGTpIService', true],
            'App\\Controller\\Admin\\AlbumController:index' => ['privates', '.service_locator.EgUKVN3', 'get_ServiceLocator_EgUKVN3Service', true],
            'App\\Controller\\Admin\\AlbumController:update' => ['privates', '.service_locator.mUnGTpI', 'get_ServiceLocator_MUnGTpIService', true],
            'App\\Controller\\Admin\\MediaController:add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\Admin\\MediaController:delete' => ['privates', '.service_locator.KP3PVQ0', 'get_ServiceLocator_KP3PVQ0Service', true],
            'App\\Controller\\Admin\\MediaController:index' => ['privates', '.service_locator.6zRW84N', 'get_ServiceLocator_6zRW84NService', true],
            'App\\Controller\\Admin\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\HomeController:guest' => ['privates', '.service_locator.fezAdO7', 'get_ServiceLocator_FezAdO7Service', true],
            'App\\Controller\\HomeController:guests' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\HomeController:portfolio' => ['privates', '.service_locator.4HCB9nm', 'get_ServiceLocator_4HCB9nmService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AlbumController::add' => '?',
            'App\\Controller\\Admin\\AlbumController::delete' => '?',
            'App\\Controller\\Admin\\AlbumController::index' => '?',
            'App\\Controller\\Admin\\AlbumController::update' => '?',
            'App\\Controller\\Admin\\MediaController::add' => '?',
            'App\\Controller\\Admin\\MediaController::delete' => '?',
            'App\\Controller\\Admin\\MediaController::index' => '?',
            'App\\Controller\\Admin\\SecurityController::login' => '?',
            'App\\Controller\\HomeController::guest' => '?',
            'App\\Controller\\HomeController::guests' => '?',
            'App\\Controller\\HomeController::portfolio' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AlbumController:add' => '?',
            'App\\Controller\\Admin\\AlbumController:delete' => '?',
            'App\\Controller\\Admin\\AlbumController:index' => '?',
            'App\\Controller\\Admin\\AlbumController:update' => '?',
            'App\\Controller\\Admin\\MediaController:add' => '?',
            'App\\Controller\\Admin\\MediaController:delete' => '?',
            'App\\Controller\\Admin\\MediaController:index' => '?',
            'App\\Controller\\Admin\\SecurityController:login' => '?',
            'App\\Controller\\HomeController:guest' => '?',
            'App\\Controller\\HomeController:guests' => '?',
            'App\\Controller\\HomeController:portfolio' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
