<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYjAIRib\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYjAIRib/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYjAIRib.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYjAIRib\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYjAIRib\App_KernelDevDebugContainer([
    'container.build_hash' => 'YjAIRib',
    'container.build_id' => 'bea197d9',
    'container.build_time' => 1779015298,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYjAIRib');
