<?php

namespace ContainerRGOaScz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KP3PVQ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KP3PVQ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KP3PVQ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'media' => ['privates', '.errored..service_locator.KP3PVQ0.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator.KP3PVQ0": it needs an instance of "App\\Entity\\Media" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'media' => 'App\\Entity\\Media',
        ]);
    }
}
