<?php

namespace ContainerRGOaScz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FezAdO7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fezAdO7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fezAdO7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guest' => ['privates', '.errored..service_locator.fezAdO7.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.fezAdO7": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'guest' => 'App\\Entity\\User',
        ]);
    }
}
