<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJKsHxwx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJKsHxwx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJKsHxwx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJKsHxwx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJKsHxwx\App_KernelDevDebugContainer([
    'container.build_hash' => 'JKsHxwx',
    'container.build_id' => '03587473',
    'container.build_time' => 1778520967,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJKsHxwx');
