<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRGOaScz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRGOaScz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRGOaScz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRGOaScz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRGOaScz\App_KernelDevDebugContainer([
    'container.build_hash' => 'RGOaScz',
    'container.build_id' => '46ec7b85',
    'container.build_time' => 1779622296,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRGOaScz');
