<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJwx4UGD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJwx4UGD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJwx4UGD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJwx4UGD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJwx4UGD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jwx4UGD',
    'container.build_id' => '35115496',
    'container.build_time' => 1778522860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJwx4UGD');
