<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'admin_album_index' => [[], ['_controller' => 'App\\Controller\\Admin\\AlbumController::index'], [], [['text', '/admin/album']], [], [], []],
    'admin_album_add' => [[], ['_controller' => 'App\\Controller\\Admin\\AlbumController::add'], [], [['text', '/admin/album/add']], [], [], []],
    'admin_album_update' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AlbumController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/album/update']], [], [], []],
    'admin_album_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AlbumController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/album/delete']], [], [], []],
    'admin_media_index' => [[], ['_controller' => 'App\\Controller\\Admin\\MediaController::index'], [], [['text', '/admin/media']], [], [], []],
    'admin_media_add' => [[], ['_controller' => 'App\\Controller\\Admin\\MediaController::add'], [], [['text', '/admin/media/add']], [], [], []],
    'admin_media_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\MediaController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/media/delete']], [], [], []],
    'admin_login' => [[], ['_controller' => 'App\\Controller\\Admin\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'guests' => [[], ['_controller' => 'App\\Controller\\HomeController::guests'], [], [['text', '/guests']], [], [], []],
    'guest' => [['id'], ['_controller' => 'App\\Controller\\HomeController::guest'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/guest']], [], [], []],
    'portfolio' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\HomeController::portfolio'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\HomeController::about'], [], [['text', '/about']], [], [], []],
];
