name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start MySQL manually
        run: |
          docker run -d \
            --name mysql \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=test_db \
            -p 3306:3306 \
            mysql:8.0

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            docker exec mysql mysqladmin ping -uroot -proot && break
            sleep 1
          done

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env.test
        run: |
          echo "APP_ENV=test" > .env.test
          echo "APP_SECRET=testsecret" >> .env.test
          echo "DATABASE_URL=\"mysql://root:root@127.0.0.1:3306/test_db?serverVersion=8.0\"" >> .env.test

      - name: Prepare database
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Run tests
        run: php bin/phpunit
